name: Continuous Deployment

on:
    pull_request:
      branches:
        - main
    workflow_dispatch:

jobs:
  push_to_registry: 
    runs-on: ubuntu-latest #L'agent utilisé est un Ubuntu
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./my-first-app/dockerfile
          push: true
          tags: sskiizens/my-first-app:latest